### PR TITLE
removed ADS-B message handling from map module and added ADSB module

### LINKED ISSUE #230: map: old ADS-B tracks are not cleared when threat is gone
Tracks build up over time when running SITL with ADS-B enabled.
screenshot from 2015-11-27 19 52 20

### PR DESCRIPTION
**Pull request by SamuelDudley**
Created a stand alone ADSB module to handle ADS-B messages
Fixes #230

### CODE REVIEW

**Comment by magicrub** [comment]
+1

**Comment by SamuelDudley** [comment]
@magicrub Are you able to confirm that the logic im using in this module matches the logic in the AP?
My understanding is that threats are active when in the threat circle and only become de-active when they clear a larger threat clear circle.

**Comment by magicrub** [comment]
I don't know Python very well so I don't feel confident confirming the source code logic, but your description is correct. However, that basic logic is a temporary placeholder for real collision detection algorithms that will replace it "soon". Hopefully someone will volunteer to do that soon.

**Comment by SamuelDudley** [comment]
Thanks. I wont be inserting complex logic in this module at this stage. Hopefully it will provide a framework to allow people developing these algorithms to visualise the result of their work.

**Comment by SamuelDudley** [comment]
Rebased off master.

**Comment by tridge** [comment]
applied, thanks!
I fixed the heading to match new mavlink definition, and made adsb module load by default

**Pull request closed without merging**
