### PR TITLE
Sphinx docs

### PR DESCRIPTION
**Pull request by hamishwillee**
This is the docs and tools to build them - as per #183.

### CODE REVIEW

**Comment by stephendade** [comment]
The old gh-pages branch and the master branch have been merged into here - they will need to be removed.
Compilation works nicely under Linux, but the files need to be output to the root folder so the main address (http://dronecode.github.io/MAVProxy/) still works.

**Comment by hamishwillee** [comment]
@stephendade Yes, the old stuff will have to be removed. 

>Compilation works nicely under Linux, but the files need to be output to the root folder so the main address (http://dronecode.github.io/MAVProxy/) still works.

The docs are built to **\MAVProxy\docs\build\html\** but there is no dependency on this chain. You can just copy the content below that point into the root and everything should work. Does that make sense?

Do I need to do anything else?

**Comment by stephendade** [comment]
@hamishwillee - it'll make things simpler from a git perspective if you cleaned up your branch before I merge it into the main tree

**Comment by hamishwillee** [comment]
Sorry? How? The branch is just source - completely clean.

**Comment by stephendade** [comment]
Use <code>git rm file</code> to delete files from your branch.
http://git-scm.com/docs/git-rm

All the previous html pages from the gh-pages branch are still in your branch

**Comment by hamishwillee** [comment]
Hi @stephendade 

Done. Sorry about that.

Cheers
H

**Comment by stephendade** [comment]
Looks good!   Thanks for doing this @hamishwillee

**Comment by stephendade** [comment]
Ok, that didn't work. Github merged it into master rather than gh-pages.

**Comment by stephendade** [comment]
Ahh, I think I see what the issue it:
@hamishwillee - Looking at the commit history on your sphinx_docs branch, you seem to have merged the master and your own changes together. Thus Github seems to think that this should be merged into master rather than gh-pages.

Could you create a new branch, based off dronecode/gh-pages and put your changes into there. Then it should cleanly merge into dronecode/gh-pages

**Comment by stephendade** [comment]
Use <code>git checkout -b branch_name dronecode/gh-pages</code> to create a new branch based on the gh-pages branch in the dronecode repo

**Comment by hamishwillee** [comment]
@stephendade My branch is supposed to merge with master - it adds the **source**. The plan would be to build the source and dump than on **gh-pages**. I thought you'd like to do that - but above it seems  you would like me to. That correct?

**Comment by stephendade** [comment]
Ahh, turns out we were thinking of different things! I'll talk to @tridge and check he's OK with putting this into master.

**Comment by hamishwillee** [comment]
Typically docs sources go in master and build go into gh-pages (in the other projects I've worked on). But yes - please check with tridge. 

I've created #186 which I think does the HTML modifications to gh-pages. This just deletes everything that was there already and then adds (in the root) the full output of my build. I hope that is correct/what is needed. If so, that should be able to go out.

**Pull request merged**
