### PR TITLE
Added Geotag log to SmartCamera Module, Added support for Sony A7R and others

### PR DESCRIPTION
**Pull request by jmachuca77**
Added a log file to the smart camera module. Currently it is located in /sdcard/log, if the path does not exist the module currently fails to load. 
Added support for more sony cameras that failed to work before due to a missing command startRecMode. 
Added Initial setting of parameters to Shutter Priority Mode, ISO Auto, Shutter Speed 1/1600. These values can be modified by sending the appropriate commands after the module is loaded, or changing the default values in the python script.

### CODE REVIEW

**Comment by magicrub** [comment]
These comitts need to be consolidated. Need any help with that?

**Comment by tridge** [comment]
it also needs a rebase. Let us know if you want some git help

**Comment by magicrub** [comment]
Here is a branch that is rebased on master and consolidated: https://github.com/magicrub/MAVProxy/tree/geotag_logger

**Comment by magicrub** [comment]
resubmitted as https://github.com/Dronecode/MAVProxy/pull/246

**Comment by jmachuca77** [comment]
Closed, resubmitted as #246

**Pull request closed without merging**
