### PR TITLE
Implements process-safe loading for wx.

### PR DESCRIPTION
**Pull request by tcr3dr**
The wx Python module is not process-safe on OS X, which causes the loading API to abort whenever a wx-based widget to be loaded. This patch enables, at minimum, the `--map` and `--console` options to be used on OS X, as well as a simple solution that will prevent regressions when developing on other platforms.

This solution is straightforward, though it involves a lot of small changes:

* `wx` is never directly loaded with `import wx`. Instead it is loaded through a helper: `from wx_loader import wx`.
* On the main thread, importing `wx_loader` throws an error (actually only on OS X, see below). The line `import wx_processguard` before `wx_loader` disables the error; this is used explicitly whenever we've forked a subprocess and want to load `wx`.

The bulk of the changes require modules which extend `wx` classes to be split from the main module object and a separate `_ui.py` companion file. You'll see that this the bulk of the changes in this PR: deleted code from files split modules into separate main, `_ui.py`, and `_util.py` files.

Because Mavproxy is a largeish codebase, we can err on the side of caution and have `wx_util.py` file only throw errors on OS X when we load `wx` on the main thread. Ideally, this causes 0 regressions on other platforms, and allows any unfixed features on OS X to be corrected over time.

Because this PR is a bit monolithic, I think it can also be split into three commits:

* Refactoring of the `_ui.py` files into separate files.
* Implementation of `wx_loader`.
* Correction of smaller changes like `wx.SimplePyApp()` => `wx.App(False)`

That would take a chunk of additional work, but whatever it takes to get these changes upstreamed.

### CODE REVIEW

**Comment by mrpollo** [comment]
@tridge I believe I had emailed you about this before, I passed this task to Tim (@tcr3dr) togheter with your notes and concerns, we are hoping we can get this merged upstream at some point

**Comment by mrpollo** [comment]
fixes #141

**Comment by stephendade** [comment]
Nice! We've been trying to figure out how to get the GUI elements running on OXS for some time now :)

**Comment by mrpollo** [comment]
whats the process to get this merged?

**Comment by tridge** [comment]
my apologies for not looking at this earlier, I haven't been looking at PRs for mavproxy for a while. I'll take a look

**Comment by tridge** [comment]
I think you may have forgotten to add some files in the PR? I don't see a wx_loader.py for example

**Comment by tcr3dr** [comment]
@tridge Files now added. I had a snafu with gitignore, how bizarre.

Thanks for looking into this!

**Comment by tcauchois** [comment]
Fixed the graph module as well in https://github.com/tcauchois/MAVProxy/commit/d9189636a9e3eaacc45e13ef6c49b34402d9b75f ... once this is merged I'll submit a pull request.

**Comment by mrpollo** [comment]
@tcr3dr maybe you want to pull @tcauchois changes into your branch so we get this merged faster

**Comment by tcauchois** [comment]
#163 incorporates both commits.

**Comment by tridge** [comment]
i'll close this one and comment in #163, which has the graph fixes

**Comment by tcr3dr** [comment]
Sounds good!

**Pull request closed without merging**
